### ISSUE TITLE
Wrong MSBuild version after updating to 1.0.1

### ISSUE THREAD

**Issue by pmoleri** [jhaker/nodejs-msbuild#17]
* Windos 10
* node: 7.4.0
* msbuild: 1.0.1

Output with version `0.3.12`:
```
  build starting
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

 finished - (0) errors

- - - - - - - - - - - - - - - -
build done
```

Output with version `1.0.1`:
```
  build starting
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
CSC : error CS1617: Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default [MainProject.csproj]
  error
undefined

 error code: 1
 failed - errors
C:\WINDOWS\microsoft.net\Framework64\v4.0.30319\msbuild.exe
```

It seems that the new version is using v4.7 in microsoft.net instead of the one in Program Files.

EDIT: removed previous nuget messages.

**Comment by pmoleri** [comment]
It started to work properly after explicitly set the msbuild version.
```
const msbuild = new Msbuild();
msbuild.version = "14.0"
...
```

I don't know why the upgrade triggered this behavior change. I'm not sure what would be the expected behavior, I certainly liked the old one better :)

**Comment by jhaker** [comment]
Corrected. Merge pull request #19 from jvopalensky/master
